alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: website-hart
        rewrite: /web/
      match:
        authority:
          exact: ""
        path:
          prefix: /
name: website-hart
region: ams
services:
  - environment_slug: php
    github:
      branch: master
      deploy_on_push: true
      repo: RoelofRuis/website-hart
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: website-hart
