<?php

return [
    [
        'id' => 1,
        'category_id' => 4,
        'name' => 'Muziektheorie',
        'slug' => 'muziektheorie',
        'cover_image' => null,
        'summary' => 'Begrijp de bouwstenen van muziek: ritme, harmonie en vormleer.',
        'description' => 'De cursus Muziektheorie helpt je muziek beter te begrijpen en bewuster te spelen of componeren. Onderwerpen zijn o.a. notenleer, ritme, toonsoorten, akkoordenleer, gehoortraining en analyse. Voor iedereen die een stevige basis of verdieping zoekt.',
        'has_trial' => false,
    ],
    [
        'id' => 2,
        'category_id' => 1,
        'name' => 'Piano',
        'slug' => 'piano',
        'cover_image' => null,
        'summary' => 'Pianolessen voor beginners en gevorderden.',
        'description' => 'Werk aan techniek, notenlezen, samenspel, improvisatie en repertoire. Individuele lessen met aandacht voor jouw niveau en muziekstijl. Instromen kan het hele jaar door; lesduur en frequentie in overleg.',
        'has_trial' => true,
    ],
    [
        'id' => 3,
        'category_id' => 1,
        'name' => 'Gitaar',
        'slug' => 'gitaar',
        'cover_image' => null,
        'summary' => 'Gitaarles voor akoestisch en elektrisch, van akkoorden tot solo.',
        'description' => 'Leer akkoorden, slag- en tokkeltechniek, tabs/notenschrift en improvisatie. Geschikt voor akoestische en elektrische gitaar. Voor starters en gevorderden; lesinhoud afgestemd op jouw doelen en favoriete muziek.',
        'has_trial' => true,
    ],
    [
        'id' => 4,
        'category_id' => 2,
        'name' => 'Het Haarlems Kamerkoor',
        'slug' => 'haarlems-kamerkoor',
        'cover_image' => null,
        'summary' => 'Gemengd kamerkoor met uitdagend repertoire in Haarlem.',
        'description' => 'Het Haarlems Kamerkoor zingt gevarieerd repertoire van renaissance tot hedendaags. We werken aan koorklank, intonatie, uitspraak en interpretatie. Auditie kan van toepassing zijn. Repetities zijn wekelijks en we geven meerdere concerten per jaar.',
        'has_trial' => false,
    ],
    [
        'id' => 5,
        'category_id' => 1,
        'name' => 'Cello',
        'slug' => 'cello',
        'cover_image' => null,
        'summary' => 'Celloles voor alle niveaus: van eerste streken tot solospel.',
        'description' => 'Ontwikkel techniek, houding en strijken; werk aan toonvorming, positie- en streektechniek en muzikaliteit. Repertoire van klassiek tot modern, met ruimte voor samenspel. Lesduur en tempo in overleg; instromen kan gedurende het jaar.',
        'has_trial' => false,
    ],
    [
        'id' => 6,
        'category_id' => 1,
        'name' => 'Accordeon',
        'slug' => 'accordeon',
        'cover_image' => null,
        'summary' => 'Accordeonles voor klavier- en knopaccordeon, solo en begeleiding.',
        'description' => 'Leer bas- en akkoordbegeleiding, melodie spelen, bellows control en ritmiek. We behandelen noten/tablatuur, stijlgevoel (volks, tango, pop, klassiek) en improvisatie. Individuele lessen op maat, geschikt voor starters en gevorderden.',
        'has_trial' => false,
    ],
    [
        'id' => 7,
        'category_id' => 1,
        'name' => 'Fagot',
        'slug' => 'fagot',
        'cover_image' => null,
        'summary' => 'Fagotles met aandacht voor embouchure, toon en intonatie.',
        'description' => 'Werk aan ademsteun, vingerzettingen, rieten en orkestpartijen/kamermuziek. Repertoire op maat en technische studies; voorbereiding op samenspel en audities mogelijk. Lesinhoud afgestemd op niveau en doelen.',
        'has_trial' => false,
    ],
    [
        'id' => 8,
        'category_id' => 1,
        'name' => 'Harp',
        'slug' => 'harp',
        'cover_image' => null,
        'summary' => 'Harples op pedaal- of Keltische harp, van basis tot podium.',
        'description' => 'We behandelen houding, handtechniek, arpeggio’s en pedaal/haakgebruik. Repertoire van klassiek tot folk/pop. Aandacht voor muzikale frasering en samenspel. Lessen individueel; instromen in overleg.',
        'has_trial' => false,
    ],
    [
        'id' => 9,
        'category_id' => 1,
        'name' => 'Blokfluit',
        'slug' => 'blokfluit',
        'cover_image' => null,
        'summary' => 'Blokfluitles voor sopraan, alt, tenor en bas.',
        'description' => 'Leer ademtechniek, articulatie en vingerzettingen. We spelen solo en in ensemble; muziek van renaissance/barok tot modern. Beginners en herintreders welkom; notenlezen en gehoortraining worden geïntegreerd.',
        'has_trial' => false,
    ],
    [
        'id' => 10,
        'category_id' => 3,
        'name' => 'Ontdek de muziek',
        'slug' => 'ontdek-de-muziek',
        'cover_image' => null,
        'summary' => 'Speelse kennismakingscursus muziek voor kinderen.',
        'description' => 'In Ontdek de muziek ervaren kinderen ritme, zang, beweging en instrumentjes in korte, afwisselende lessen. We stimuleren luistervaardigheid en samenspel op een speelse manier. Ideaal als opstap naar instrument- of zanglessen.',
        'has_trial' => false,
    ]
];
