<?php

return [
    [
        'id' => 1,
        'parent_id' => null,
        'name' => 'Instrumenten & Zang',
        'slug' => 'instrumenten-zang',
        'cover_image' => null,
        'summary' => 'Ontdek alle instrument- en zangcursussen, van beginner tot gevorderd.',
        'description' => 'Deze overzichtspagina bundelt al onze lessen voor instrumenten en zang. Kies je instrument of stemsoort en vind lessen op elk niveau, voor jong en oud. Op deze pagina zie je een introductie per instrument en verwijzingen naar alle beschikbare cursussen.',
        'is_taught' => false,
    ],
    [
        'id' => 2,
        'parent_id' => null,
        'name' => 'Samenspel & Koren',
        'slug' => 'samenspel-koren',
        'cover_image' => null,
        'summary' => 'Samen muziek maken in ensembles, bands en koren.',
        'description' => 'Muziek maak je samen! Op deze pagina vind je al onze samenspelgroepen, ensembles, bands en koren. Er zijn groepen voor verschillende leeftijden en niveaus. Klik door naar een ensemble of koor dat bij jou past en ontdek repetitietijden, repertoire en optredens.',
        'is_taught' => false,
    ],
    [
        'id' => 3,
        'parent_id' => null,
        'name' => 'Kindercursussen',
        'slug' => 'kindercursussen',
        'cover_image' => null,
        'summary' => 'Speelse muziekcursussen voor kinderen om talent te ontdekken.',
        'description' => 'Speciaal voor kinderen bieden we laagdrempelige en speelse cursussen aan. Kinderen maken spelenderwijs kennis met muziek, ritme en samenspel. Op deze pagina vind je alle kindercursussen overzichtelijk bij elkaar, met heldere uitleg per cursus.',
        'is_taught' => false,
    ],
    [
        'id' => 4,
        'parent_id' => null,
        'name' => 'Compositie',
        'slug' => 'compositie',
        'cover_image' => null,
        'summary' => 'Leer je eigen muziek schrijven en arrangeren.',
        'description' => 'In de cursus Compositie werk je aan melodie, harmonie, vorm en instrumentatie. Je ontwikkelt je eigen muzikale ideeën tot complete stukken. Geschikt voor gemotiveerde beginners en gevorderde makers. Lesinhoud kan worden afgestemd op jouw niveau en stijl.',
        'is_taught' => true,
    ],
    [
        'id' => 5,
        'parent_id' => null,
        'name' => 'Muziektheorie',
        'slug' => 'muziektheorie',
        'cover_image' => null,
        'summary' => 'Begrijp de bouwstenen van muziek: ritme, harmonie en vormleer.',
        'description' => 'De cursus Muziektheorie helpt je muziek beter te begrijpen en bewuster te spelen of componeren. Onderwerpen zijn o.a. notenleer, ritme, toonsoorten, akkoordenleer, gehoortraining en analyse. Voor iedereen die een stevige basis of verdieping zoekt.',
        'is_taught' => true,
    ],
    [
        'id' => 6,
        'parent_id' => 1,
        'name' => 'Piano',
        'slug' => 'piano',
        'cover_image' => null,
        'summary' => null,
        'description' => null,
        'is_taught' => true,
    ],
    [
        'id' => 7,
        'parent_id' => 1,
        'name' => 'Gitaar',
        'slug' => 'gitaar',
        'cover_image' => null,
        'summary' => null,
        'description' => null,
        'is_taught' => true,
    ],
    [
        'id' => 8,
        'parent_id' => 2,
        'name' => 'Het Haarlems Kamerkoor',
        'slug' => 'haarlems-kamerkoor',
        'cover_image' => null,
        'summary' => null,
        'description' => null,
        'is_taught' => true,
    ]
];
