<?php

use app\models\LessonFormat;

return [
    [
        'id' => 1,
        'course_id' => 6,
        'teacher_id' => 7, // Gina Vos
        'persons_per_lesson' => 1,
        'duration_minutes' => 30,
        'weeks_per_year' => 36,
        'frequency' => 'wekelijks',
        'price_per_person' => 22.50,
        'price_display_type' => LessonFormat::PRICE_DISPLAY_PER_PERSON,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'sun' => false,
        'use_custom_location' => false,
        'location_id' => 1,
        'location_custom' => null,
    ],
    [
        'id' => 2,
        'course_id' => 6,
        'teacher_id' => 7, // Gina Vos
        'persons_per_lesson' => 2,
        'duration_minutes' => 45,
        'weeks_per_year' => 36,
        'frequency' => 'wekelijks',
        'price_per_person' => 17.50,
        'price_display_type' => LessonFormat::PRICE_DISPLAY_PER_PERSON,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'sun' => false,
        'use_custom_location' => false,
        'location_id' => 1,
        'location_custom' => null,
    ],
    [
        'id' => 3,
        'course_id' => 7,
        'teacher_id' => 2, // Bob Jansen
        'persons_per_lesson' => 4,
        'duration_minutes' => 60,
        'weeks_per_year' => 34,
        'frequency' => 'wekelijks',
        'price_per_person' => 12.00,
        'price_display_type' => LessonFormat::PRICE_DISPLAY_PER_PERSON,
        'mon' => false,
        'tue' => false,
        'wed' => false,
        'thu' => true,
        'fri' => false,
        'sat' => false,
        'sun' => false,
        'use_custom_location' => false,
        'location_id' => 2,
        'location_custom' => null,
    ],
    [
        'id' => 4,
        'course_id' => 4,
        'teacher_id' => 6, // Ferry Kuipers
        'persons_per_lesson' => 1,
        'duration_minutes' => 60,
        'weeks_per_year' => 30,
        'frequency' => 'tweewekelijks',
        'price_per_person' => 35.00,
        'price_display_type' => LessonFormat::PRICE_DISPLAY_PER_PERSON,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'sun' => false,
        'use_custom_location' => false,
        'location_id' => 1,
        'location_custom' => null,
    ],
    [
        'id' => 5,
        'course_id' => 5,
        'teacher_id' => 10, // Joris Willems
        'persons_per_lesson' => 8,
        'duration_minutes' => 90,
        'weeks_per_year' => 32,
        'frequency' => 'wekelijks',
        'price_per_person' => 9.50,
        'price_display_type' => LessonFormat::PRICE_DISPLAY_PER_PERSON,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'sun' => false,
        'use_custom_location' => false,
        'location_id' => 2,
        'location_custom' => null,
    ],
    [
        'id' => 6,
        'course_id' => 8,
        'teacher_id' => 5, // Eva Smits
        'persons_per_lesson' => 30,
        'duration_minutes' => 120,
        'weeks_per_year' => 30,
        'frequency' => 'wekelijks',
        'price_per_person' => null, // prijs op aanvraag
        'price_display_type' => LessonFormat::PRICE_DISPLAY_HIDDEN,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'sun' => false,
        'use_custom_location' => false,
        'location_id' => 2,
        'location_custom' => null,
    ],
];
