<?php

return [
    [
        'id' => 1,
        'course_id' => 1,
        'teacher_id' => 1,
        'persons_per_lesson' => 1,
        'duration_minutes' => 60,
        'weeks_per_year' => 40,
        'frequency' => 'weekly',
        'price_per_person' => 30.00,
        'mon' => 1,
        'tue' => 0,
        'wed' => 0,
        'thu' => 1,
        'fri' => 0,
        'sat' => 0,
        'sun' => 0,
        'location' => 'Studio A',
        'show_price' => 1,
        'created_at' => 1700000000,
        'updated_at' => 1700000000,
    ],
    [
        'id' => 2,
        'course_id' => 1,
        'teacher_id' => 2,
        'persons_per_lesson' => 2,
        'duration_minutes' => 45,
        'weeks_per_year' => 30,
        'frequency' => 'biweekly',
        'price_per_person' => 20.00,
        'mon' => 0,
        'tue' => 1,
        'wed' => 1,
        'thu' => 0,
        'fri' => 0,
        'sat' => 0,
        'sun' => 0,
        'location' => 'Online',
        'show_price' => 0,
        'created_at' => 1700000000,
        'updated_at' => 1700000000,
    ],
    [
        'id' => 3,
        'course_id' => 2,
        'teacher_id' => 1,
        'persons_per_lesson' => 4,
        'duration_minutes' => 90,
        'weeks_per_year' => 20,
        'frequency' => 'monthly',
        'price_per_person' => 15.50,
        'mon' => 0,
        'tue' => 0,
        'wed' => 0,
        'thu' => 0,
        'fri' => 1,
        'sat' => 0,
        'sun' => 1,
        'location' => 'Community Center',
        'show_price' => 1,
        'created_at' => 1700000000,
        'updated_at' => 1700000000,
    ],
];
