<?php

return [
    ['id' => 2, 'name' => 'Piano'],
    ['id' => 4, 'name' => 'Gitaar'],
    ['id' => 5, 'name' => 'Jazz'],
    ['id' => 6, 'name' => 'Pop'],
    ['id' => 8, 'name' => 'Viool'],
    ['id' => 10, 'name' => 'Drums'],
    ['id' => 11, 'name' => 'Slagwerk'],
    ['id' => 13, 'name' => 'Zang'],
    ['id' => 14, 'name' => 'Ademtechniek'],
    ['id' => 15, 'name' => 'Podiumpresentatie'],
    ['id' => 17, 'name' => 'Saxofoon'],
    ['id' => 18, 'name' => 'Improvisatie'],
    ['id' => 19, 'name' => 'Muziektheorie'],
    ['id' => 22, 'name' => 'Basgitaar'],
    ['id' => 23, 'name' => 'Bandcoaching'],
    ['id' => 25, 'name' => 'Cello'],
    ['id' => 26, 'name' => 'Kamermuziek'],
    ['id' => 27, 'name' => 'Orkestspel'],
    ['id' => 29, 'name' => 'Klarinet'],
    ['id' => 30, 'name' => 'Dwarsfluit'],
    ['id' => 31, 'name' => 'Kamerkoor'],
    ['id' => 32, 'name' => 'Accordeon'],
    ['id' => 33, 'name' => 'Fagot'],
    ['id' => 35, 'name' => 'Blokfluit'],
    ['id' => 36, 'name' => 'Kinderen'],
    ['id' => 37, 'name' => 'Ontdek de muziek'],
    ['id' => 38, 'name' => 'Copyright'],
    ['id' => 39, 'name' => 'Auteursrecht'],
    ['id' => 40, 'name' => 'Over de vereniging'],
    ['id' => 41, 'name' => 'Bestuur'],
    ['id' => 42, 'name' => 'Organisatie'],
    ['id' => 43, 'name' => 'Contact'],
    ['id' => 44, 'name' => 'Privacy'],
    ['id' => 45, 'name' => 'AVG'],
    ['id' => 46, 'name' => 'Persoonsgegevens'],
    ['id' => 47, 'name' => 'Locaties'],
];
