<?php

return [
    ['teacher_id' => 1, 'tag_id' => 2],
    ['teacher_id' => 2, 'tag_id' => 4],
    ['teacher_id' => 2, 'tag_id' => 5],
    ['teacher_id' => 2, 'tag_id' => 6],
    ['teacher_id' => 3, 'tag_id' => 8],
    ['teacher_id' => 4, 'tag_id' => 10],
    ['teacher_id' => 4, 'tag_id' => 11],
    ['teacher_id' => 5, 'tag_id' => 13],
    ['teacher_id' => 5, 'tag_id' => 14],
    ['teacher_id' => 5, 'tag_id' => 15],
    ['teacher_id' => 6, 'tag_id' => 17],
    ['teacher_id' => 6, 'tag_id' => 18],
    ['teacher_id' => 6, 'tag_id' => 19],
    ['teacher_id' => 7, 'tag_id' => 2],
    ['teacher_id' => 8, 'tag_id' => 22],
    ['teacher_id' => 8, 'tag_id' => 23],
    ['teacher_id' => 9, 'tag_id' => 25],
    ['teacher_id' => 9, 'tag_id' => 26],
    ['teacher_id' => 9, 'tag_id' => 27],
    ['teacher_id' => 10, 'tag_id' => 29],
    ['teacher_id' => 10, 'tag_id' => 30],
];
