<?php

return [
    [
        'id' => 1,
        'full_name' => 'Alice van Dijk',
        'slug' => 'alice-van-dijk',
        'description' => 'Hoofddocent piano en ensemble, met 15 jaar ervaring.',
        'email' => 'alice@example.com',
        'website' => 'https://example.com/teachers/alice-van-dijk',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => true,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 2,
        'full_name' => 'Bob Jansen',
        'slug' => 'bob-jansen',
        'description' => 'Gitaarleraar gespecialiseerd in jazz en pop.',
        'email' => 'bob@example.com',
        'website' => 'https://example.com/teachers/bob-jansen',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 3,
        'full_name' => 'Carla de Vries',
        'slug' => 'carla-de-vries',
        'description' => 'Viooldocent met focus op techniek en muzikaliteit.',
        'email' => 'carla@example.com',
        'website' => 'https://example.com/teachers/carla-de-vries',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 4,
        'full_name' => 'Daan Bakker',
        'slug' => 'daan-bakker',
        'description' => 'Docent drums en ritmiek, groeps- en privélessen.',
        'email' => 'daan@example.com',
        'website' => 'https://example.com/teachers/daan-bakker',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 5,
        'full_name' => 'Eva Smits',
        'slug' => 'eva-smits',
        'description' => 'Zangcoach, met aandacht voor ademtechniek en podiumpresentatie.',
        'email' => 'eva@example.com',
        'website' => 'https://example.com/teachers/eva-smits',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 6,
        'full_name' => 'Ferry Kuipers',
        'slug' => 'ferry-kuipers',
        'description' => 'Saxofoondocent, improvisatie en muziektheorie.',
        'email' => 'ferry@example.com',
        'website' => 'https://example.com/teachers/ferry-kuipers',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 7,
        'full_name' => 'Gina Vos',
        'slug' => 'gina-vos',
        'description' => 'Pianodocent voor beginners en gevorderden.',
        'email' => 'gina@example.com',
        'website' => 'https://example.com/teachers/gina-vos',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 8,
        'full_name' => 'Hugo Meijer',
        'slug' => 'hugo-meijer',
        'description' => 'Basgitaar en bandcoaching.',
        'email' => 'hugo@example.com',
        'website' => 'https://example.com/teachers/hugo-meijer',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 9,
        'full_name' => 'Iris de Boer',
        'slug' => 'iris-de-boer',
        'description' => 'Cellodocent, kamermuziek en orkestspel.',
        'email' => 'iris@example.com',
        'website' => 'https://example.com/teachers/iris-de-boer',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 10,
        'full_name' => 'Joris Willems',
        'slug' => 'joris-willems',
        'description' => 'Klarinet- en dwarsfluitdocent.',
        'email' => 'joris@example.com',
        'website' => 'https://example.com/teachers/joris-willems',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => false,
        'is_active' => true,
        'is_teaching' => true,
        'last_login' => null,
    ],
    [
        'id' => 11,
        'full_name' => 'Kristof van der Waal',
        'slug' => 'kristof-van-der-waal',
        'description' => 'Content manager van de vereniging',
        'email' => 'kristof@example.com',
        'website' => '',
        'telephone' => null,
        'profile_picture' => null,
        'password_hash' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'auth_key' => null,
        'is_admin' => true,
        'is_active' => true,
        'is_teaching' => false,
        'last_login' => null,
    ]
];
