<?php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'slug' => 'alice-van-dijk',
        'description' => 'Hoofddocent piano en ensemble, met 15 jaar ervaring.',
        'website' => 'https://example.com/teachers/alice-van-dijk',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 2,
        'user_id' => 2,
        'slug' => 'bob-jansen',
        'description' => 'Gitaarleraar gespecialiseerd in jazz en pop.',
        'website' => 'https://example.com/teachers/bob-jansen',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 3,
        'user_id' => 3,
        'slug' => 'carla-de-vries',
        'description' => 'Viooldocent met focus op techniek en muzikaliteit.',
        'website' => 'https://example.com/teachers/carla-de-vries',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 4,
        'user_id' => 4,
        'slug' => 'daan-bakker',
        'description' => 'Docent drums en ritmiek, groeps- en privélessen.',
        'website' => 'https://example.com/teachers/daan-bakker',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 5,
        'user_id' => 5,
        'slug' => 'eva-smits',
        'description' => 'Zangcoach, met aandacht voor ademtechniek en podiumpresentatie.',
        'website' => 'https://example.com/teachers/eva-smits',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 6,
        'user_id' => 6,
        'slug' => 'ferry-kuipers',
        'description' => 'Saxofoondocent, improvisatie en muziektheorie.',
        'website' => 'https://example.com/teachers/ferry-kuipers',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 7,
        'user_id' => 7,
        'slug' => 'gina-vos',
        'description' => 'Pianodocent voor beginners en gevorderden.',
        'website' => 'https://example.com/teachers/gina-vos',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 8,
        'user_id' => 8,
        'slug' => 'hugo-meijer',
        'description' => 'Basgitaar en bandcoaching.',
        'website' => 'https://example.com/teachers/hugo-meijer',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 9,
        'user_id' => 9,
        'slug' => 'iris-de-boer',
        'description' => 'Cellodocent, kamermuziek en orkestspel.',
        'website' => 'https://example.com/teachers/iris-de-boer',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
    [
        'id' => 10,
        'user_id' => 10,
        'slug' => 'joris-willems',
        'description' => 'Klarinet- en dwarsfluitdocent.',
        'website' => 'https://example.com/teachers/joris-willems',
        'telephone' => null,
        'profile_picture' => null,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => true,
        'sun' => true,
    ],
];
